lsudo: required
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - g++-8
            - boost1.68
            - valgrind
            - libgl1-mesa-dev
      env:
      - C_COMPILER=gcc-8
      - CXX_COMPILER=g++-8
      - TRAVIS_DIST_NAME=bionic
      
dist: bionic

before_install:
  - sudo add-apt-repository main
  - sudo add-apt-repository universe
  - sudo add-apt-repository restricted
  - sudo add-apt-repository multiverse
  - sudo apt-get update -y

install:
  - sudo apt-get install build-essential libgtk-3-dev
  - sudo apt install -yq libsfml-dev

script:
  - mkdir build
  - cd build
  - env CC=${C_COMPILER} CXX=${CXX_COMPILER} cmake .. -DENABLE_COVERAGE:BOOL=TRUE -DCMAKE_BUILD_TYPE=DEBUG
  - echo "We have" `nproc` "cores here"
  - make -j `nproc`
  - ctest -j `nproc` -V

after_success:
  - bash <(curl -s https://codecov.io/bash) -x gcov-8
