multipleFilesAnimators:
  - name: player
    animations:
      - type: idle
        firstTexturePath: resources/Player/Idle/idle-with-weapon-1.png
        numberOfTextures: 6
        timeBetweenTexturesInSeconds: 0.3
      - type: walk
        firstTexturePath: resources/Player/Walk/walk-with-weapon-1.png
        numberOfTextures: 11
        timeBetweenTexturesInSeconds: 0.1

singleFileAnimators:
  - name: bunny
    animations:
      - type: idle
        texturePath: resources/bunny-hop-spritesheet.png
        textureWidthInPixels: 192
        textureHeightInPixels: 128
        startXPosition: 40
        startYPosition: 64
        rectToCutWidthInPixels: 40
        rectToCutHeightInPixels: 32
        numberOfTextures: 1
        timeBetweenTexturesInSeconds: 0.14
      - type: walk
        texturePath: resources/bunny-hop-spritesheet.png
        textureWidthInPixels: 192
        textureHeightInPixels: 128
        startXPosition: 0
        startYPosition: 32
        rectToCutWidthInPixels: 48
        rectToCutHeightInPixels: 32
        numberOfTextures: 4
        timeBetweenTexturesInSeconds: 0.1
