multipleFilesAnimators:
  - name: player
    animations:
      - type: idle
        numberOfTextures: 6
        timeBetweenTexturesInSeconds: 0.3
        loopsAllowed: true
        interruptionAllowed: true