multipleFilesAnimators:
  - name: player
    animations:
      - type: idle
        firstTexturePath: resources/Player/Idle/idle-with-weapon-1.png
        numberOfTextures: 6
        timeBetweenTexturesInSeconds: 0.3
        loopsAllowed: true
        interruptionAllowed: true
      - type: walk
        firstTexturePath: resources/Player/Walk/walk-with-weapon-1.png
        numberOfTextures: 11
        timeBetweenTexturesInSeconds: 0.7
        loopsAllowed: true
        interruptionAllowed: true

  - name: enemy
    animations:
      - type: idle
        firstTexturePath: resources/Enemy/Idle/idle-with-weapon-1.png
        numberOfTextures: 3
        timeBetweenTexturesInSeconds: 0.4
        loopsAllowed: true
        interruptionAllowed: true
      - type: walk
        firstTexturePath: resources/Enemy/Walk/walk-with-weapon-1.png
        numberOfTextures: 2
        timeBetweenTexturesInSeconds: 0.8
        loopsAllowed: true
        interruptionAllowed: true

